---
name: TAG-Security-Linter

# Run this workflow on every PR to main
on:
  pull_request:
    branches:
      - main

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: make setup
  Lint:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint
  Spelling:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v4
      - name: Spelling
        run: make spelling
  Links:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v4
      - name: Links
        run: make links
